#!/usr/bin/env node
/**
 * Regenerates src/generated/schema.ts from the OpenAPI contract (gate 1.1:
 * "OpenAPI is the contract; ... clients are GENERATED, never hand-written").
 *
 * Source resolution order:
 *   1. OPENAPI_URL env var (e.g. http://backend:8000/openapi.json in CI,
 *      pointed at the running `backend:test` service) — the live contract.
 *   2. ../openapi.json — a committed snapshot, used for local dev when no
 *      backend is running. `web:client-drift` (see .gitlab-ci.yml) fails the
 *      pipeline if this snapshot has drifted from the live contract, so it
 *      can never silently go stale.
 *
 * Usage:
 *   npm run generate:client                 # snapshot
 *   OPENAPI_URL=http://localhost:8000/openapi.json npm run generate:client
 */
import { writeFile, readFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';

const here = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(here, '../src/generated/schema.ts');
const snapshotFile = path.join(here, '../openapi.json');

async function loadSchema() {
  const url = process.env.OPENAPI_URL;
  if (url) {
    console.log(`[generate:client] fetching live OpenAPI contract from ${url}`);
    const res = await fetch(url);
    if (!res.ok) throw new Error(`OPENAPI_URL fetch failed: ${res.status} ${res.statusText}`);
    return res.json();
  }
  console.log(`[generate:client] no OPENAPI_URL set — using committed snapshot ${snapshotFile}`);
  return JSON.parse(await readFile(snapshotFile, 'utf8'));
}

const schema = await loadSchema();
const ast = await openapiTS(schema);
const header =
  '/* eslint-disable */\n' +
  '// AUTO-GENERATED by `npm run generate:client` (packages/api-client/scripts/generate.mjs).\n' +
  '// Do not hand-edit — regenerate from the OpenAPI contract instead (gate 1.1).\n\n';

await mkdir(path.dirname(outFile), { recursive: true });
await writeFile(outFile, header + astToString(ast));
console.log(`[generate:client] wrote ${outFile}`);
